### ISSUE TITLE
the new function: af_save_field_to_post does not work with ACF clone fields

### ISSUE THREAD

**Issue by asitemade4u** [advancedforms/advanced-forms#10] opened 2017-04-16 14:42 UTC
Please see comments at the end of the closed #5 issue.
I did a thorough testing on that.

**Comment by Fabianlindfors** [comment] 2017-04-16 18:59
Thanks again for looking into this!

I didn't have the clone field in mind while creating the new helper function and it doesn't really work as intended with cloned fields. I have been looking into this for a little while now and I'm closing in on a solution.

Will push a commit as soon as I have found a solution. Full support for clone fields would be great. :)

**Comment by asitemade4u** [comment] 2017-04-16 19:00
Thank you SO MUCH Fabian, you are saving my day again.

Yes, clone fields are very powerful and full of potential. I sent you a 
private email on the subject.

Stephen Sinclair
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
email: stephen@aSiteMade4U.com <mailto:stephen@aSiteMade4U.com>
web: aSiteMade4U.com 
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
cell: (914) 334-2929

**Comment by asitemade4u** [comment] 2017-04-16 19:37
Another weird side-effect of the clone fields is that the Selects do not work at all:

- fields are displayed in Advanced Forms. Selects too
- but Selects do not display anything -- I checked, and the same Select works in the backend metabox.

**Comment by asitemade4u** [comment] 2017-04-24 21:37
Hi Fabian, any update on the subject of Clone fields?

**Comment by asitemade4u** [comment] 2017-04-25 00:00
Hi Fabian,
Another part of the plugin that does not work with the Cloned Fields: when defining the email to send after the form is submitted:
- address of the addressee of the email: choice popup is empty

**Comment by Fabianlindfors** [comment] 2017-04-25 19:35
Hi!

I just pushed a commit (f24b919434312d9055e7a22368b32a4e2de83d2c) with some fixes for clone fields. I have tried to fix the problems with getting values from clone fields and saving them with `af_save_field_to_post`. I have barely had any time to test it out so it would be great if you could try it and give some feedback!

These changes do not fix the issues with emails and selecting recipients. Going to have to check that out next. :)

**Comment by asitemade4u** [comment] 2017-04-25 19:36
Thanks Fabian, will test this afternoon!

Stephen Sinclair
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
email: stephen@aSiteMade4U.com <mailto:stephen@aSiteMade4U.com>
web: aSiteMade4U.com 
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
cell: (914) 334-2929

**Comment by asitemade4u** [comment] 2017-04-25 20:26
I have proceeded with the tests and **it worked perfectly!**

**Comment by Fabianlindfors** [comment] 2017-04-27 16:37
Thanks for testing!

Could you provide me with a screenshot of your field group configurations and the code used to save your form?

**Comment by asitemade4u** [comment] 2017-04-27 17:56
Hi Fabian,
Will do better when I am back: will let you access the staging website 
as an admin.
Please provide your private email so that I can forward credentials.

**Comment by Fabianlindfors** [comment] 2017-05-25 20:17
Hi again!

I've rewritten the way field parsing and saving is handled in the new version 1.2.0. It now closely mimics the way ACF works to ensure compatibility.

Thanks to this change clone fields also work much better. Values of clone fields can be retrieved using `af_get_field` and they can also be saved directly to a post using `af_save_field_to_post`. With the testing I have done it seems to work.

One thing to note is that when using `af_save_field_to_post` you must pass the actual clone fields name and not the individual cloned fields (all cloned fields will be saved). It's a bit inconvenient but I hope to solve it in an upcoming release.

Feel free to test it out if you have the time. I hope it solves the problems you were having. :)

**Comment by Fabianlindfors** [comment] 2017-07-10 21:00
Closing because of inactivity. Should be fixed since 1.2.0.

**Closed by Fabianlindfors** 2017-07-10 21:00 UTC
